version: '3'
services:
  nginx:
    image: nginx:stable
    environment:
      TZ: Asia/Taipei
    volumes:
      - ./nginx/nginx.crt:/usr/share/nginx/ssl/nginx.crt
      - ./nginx/nginx.key:/usr/share/nginx/ssl/nginx.key
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/volume/cache:/etc/nginx/cache
      - ./nginx/volume/log:/var/log/nginx
    depends_on:
      - server
    networks:
      - public
    ports:
      - 80:80
      - 443:443
    restart: always

  server:
    build:
      context: .
      target: deploy-container
    image: visual-ai-agent-designer/server:1.0.0
    expose:
      - 3000
      - 3001
    environment:
      - TZ=Asia/Taipei
      - TWCC_API_URL=https://api-ams.twcc.ai/api
      - TWCC_API_KEY=xxxxxx-xxxxxx-xxxxxx
    networks:
      - public
      - private


networks:
  public:
  private:
