# version: '3'
services:
  nginx:
    image: nginx:stable
    environment:
      TZ: Asia/Taipei
    volumes:
      - ./nginx/nginx.crt:/usr/share/nginx/ssl/nginx.crt
      - ./nginx/nginx.key:/usr/share/nginx/ssl/nginx.key
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/volume/cache:/etc/nginx/cache
      - ./nginx/volume/log:/var/log/nginx
    depends_on:
      - server
    networks:
      - public
    ports:
      - 80:80
      - 443:443
      - 3001:3001
    restart: always
    
  postgres:
    build: ./postgres
    image: graph-ai-agent-designer/postgresdb:1.0.0
    shm_size: 128mb
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: my-password
      POSTGRES_DB: postgres
    networks:
      - private
    expose:
      - 5432
    restart: always

  server:
    build:
      context: .
      target: deploy-container
    image: graph-ai-agent-designer/server:1.1.0
    expose:
      - 3000
      - 3001
    environment:
      - TZ=Asia/Taipei
      - OPENAI_API_KEY=<your-openai-api-key>
    networks:
      - public
      - private
      
  develop:
    build:
      context: .
      target: base-container
    image: graph-ai-agent-designer/server:dev
    expose:
      - 3000
      - 3001
    environment:
      - TZ=Asia/Taipei
      - OPENAI_API_KEY=<your-openai-api-key>
    networks:
      - public
      - private
    volumes:
      - .:/root/ai-agent
    working_dir: /root/ai-agent
    command: bash
    stdin_open: true
    tty: true

networks:
  public:
  private:
